# %player% - имя игрока

quest-1:
  line-1:
    - "give %player% diamond 1"
  line-2:
  line-3: []
  line-4: []
  line-5: []

quest-2:
  line-1: []
  line-2: []
  line-3: []
  line-4: []
  line-5: []

quest-3:
  line-1: []
  line-2: []
  line-3: []
  line-4: []
  line-5: []
